site_name: MinhasHoras
nav:
    - Home: index.md
    - Concepts and Terms: concepts_and_terms.md
    - Features:
        - 'Clients': features/clients.md
        - 'Projects': features/projects.md
    - 'API Reference': minhashoras_api/api_project.md
    - 'Web App Reference': minhashoras_app/app_project.md
    - Documentation:
          - 'MkDocs': minhashoras_docs/docs_project.md
          - 'Usage Examples': minhashoras_docs/mkdocs_usage_examples.md
theme:
    name: material
    language: pt-BR

plugins:
    - macros
    - search

markdown_extensions:
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format

extra:
    group_test:
        test_macro: This is a macro test value.
