site_name: MinhasHoras
nav:
    - Home: index.md
    - Concepts and Terms: concepts_and_terms.md
    - Features:
        - 'Clients': features/clients.md
        - 'Projects': features/projects.md
    - 'API Reference': minhashoras_api/api_project.md
    - 'Web App Reference': minhashoras_app/app_project.md
    - 'Documentation': minhashoras_docs/docs_project.md
theme:
    name: material
    language: pt-BR
